### ISSUE TITLE
aws_route_table resource doesn't accept vpc_id

### ISSUE THREAD

**Issue by asimonrose** [mattray/inspec-iggy#24]
I'm running Inspec 3.7.11 with Iggy 0.4.0 against AWS resources and a local terraform(0.11.11) state file. 

Once I've revised the 'should eq' -> 'should cmp' my only errors are using the aws_route_table resource.  The Inspec Iggy output looks for vpc_id in the route table output, and that's not a supported parameter in Inspec 3.  

Thanks in advance.
Simon

**Comment by mattray** [comment]
Looks like I opened an issue against this a long time ago https://github.com/inspec/inspec-aws/issues/32

I'll reinvestigate this for the upcoming 0.5.0 release
