### ISSUE TITLE
Using inspec-iggy with remote .tfstate

### ISSUE THREAD

**Issue by richjamesgreen** [mattray/inspec-iggy#3]
I'm really interested in using this but our state files are located remotely in s3 buckets. 
Could this plugin have the ability to target the remote state when running:
inspec terraform generate --tfstate <s3 state location>

**Comment by pcanham** [comment]
Interested in this as well, but unsure whether this might already be fixed/handled within the inspec provisioner plugin for terraform.

**Comment by tbugfinder** [comment]
Our state files are stored remotely in Consul.

**Comment by tbugfinder** [comment]
> @richjamesgreen Just out of interesst, how does terraform handle the case with a remote state file?

This is a core element of terraform.

**Comment by mattray** [comment]
This will be supported in the upcoming 0.5.0 release https://github.com/mattray/inspec-iggy/tree/0.5.0.

I'll go through the Terraform and CloudFormation docs and see what the formats they use are (http:, https:, s3:, anything else?). I'm planning on leaving the CLI alone (still -t) and parsing the string for remote sources.

**Comment by mattray** [comment]
Looking through the Terraform docs for remote state, there are quite a few supported options. 
https://www.terraform.io/docs/backends/types/index.html

For the 0.5.0 release I'll probably only support http/https/s3 and see what sort of feedback I get. For the other backends of Terraform we'll probably need to either wrap the Terraform command or find an Terraform Ruby SDK we can reuse.

**Comment by richjamesgreen** [comment]
Yes we use S3 and the Azurerm types most frequently. But trialling in S3 would be really useful!

**Comment by asimonrose** [comment]
I’d definitely like to see the S3 remote state file supported - that’d be great.

**Comment by samuelmoneill** [comment]
Has this been resolved? is it possible to run
`inspec terraform generate --tfstate s3://path/to/terraform.tfstate --name myprofile`

**Comment by tbugfinder** [comment]
We use CONSUL for storing the state.

**Comment by mattray** [comment]
I'm trying to finish 0.5.0, which will support http/https/s3 but not Consul. I'm open to suggestions for an easy way to support all the Terraform backends in the next release.

**Comment by mattray** [comment]
0.5.0 supports http/https/s3 but not Consul. I'm open to suggestions for an easy way to support all the Terraform backends in the next release.
