### ISSUE TITLE
empty generated.rb

### ISSUE THREAD

**Issue by dwizzle204** [mattray/inspec-iggy#37]
**Describe the bug**
generated inspec file is empty except for title

```cat generated.rb
title "InSpec Profile: generated by Iggy v0.8.0"
```

**Environment**
InSpec Profile: generated by Iggy v0.8.0
inspec -v
4.18.97
terraform --version
Terraform v0.12.20
depends:
- name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/master.tar.gz

**To Reproduce**
Create a simple resource group and run inspec against the state file
inspec terraform generate --tfstate terraform.tfstate --name terraform --platform azure --resourcepath ~/inspec/inspec-azure

───────────────────────── InSpec Iggy Code Generator ─────────────────────────

Creating new profile at /terraform/az-test/terraform
 • Creating file README.md
 • Creating directory controls
 • Creating file controls/generated.rb
 • Creating file inspec.yml

**Expected behavior**
expecting some tests to be defined from the state file

**Additional context**

**Comment by mattray** [comment]
I was able to recreate something similar recently. There was a regression in the recent release of InSpec, I'm waiting for them to tell me they've fixed it and I'll circle back and re-verify this. I think I went back to 4.18.50 or so and it worked, but I'll keep you posted on it.

**Comment by dwizzle204** [comment]
No luck with https://downloads.chef.io/inspec/stable/4.18.51

**Comment by dwizzle204** [comment]
Fixed in inspec-4.18.100
